using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Windows.Input;
using System.Xml.Linq;

namespace AntDesignToolbox.ToolWindows.ViewModels
{
    public class IconTypePropertyViewModel : PropertyItemViewModel
    {
        private StringOptionItemViewModel _selectedTheme;
        public StringOptionItemViewModel SelectedTheme
        {
            get => _selectedTheme;
            set
            {
                SetProperty(ref _selectedTheme, value);
                if(value.Value == "@IconThemeType.Fill")
                {
                    Types = _filledTypes;
                }
                else if(value.Value== "@IconThemeType.Outline")
                {
                    Types = _outlinedTypes;
                }
                else if(value.Value == "@IconThemeType.Twotone")
                {
                    Types = _twoToneTypes;
                }
            }
        }

        private ObservableCollection<StringOptionItemViewModel> _themes;
        public ObservableCollection<StringOptionItemViewModel> Themes
        {
            get => _themes;
            set => SetProperty(ref _themes, value);
        }

        private StringOptionItemViewModel _selectedType;
        public StringOptionItemViewModel SelectedType
        {
            get => _selectedType;
            set => SetProperty(ref _selectedType, value);
        }

        private ObservableCollection<StringOptionItemViewModel> _types;
        public ObservableCollection<StringOptionItemViewModel> Types
        {
            get { return _types; }
            set { SetProperty(ref _types, value); }
        }


        public IconTypePropertyViewModel()
        {
            Themes = new ObservableCollection<StringOptionItemViewModel>()
            {
                new StringOptionItemViewModel("Filled", "@IconThemeType.Fill"),
                new StringOptionItemViewModel("Outlined", "@IconThemeType.Outline"),
                new StringOptionItemViewModel("Two Tone", "@IconThemeType.Twotone"),
            };
            SelectedTheme = Themes[0];
            Types = _filledTypes;

        }


        public override ICommand ResetCommand { get; set; }



        public override IEnumerable<XAttribute> ConvertToAttributes()
        {
            if (SelectedTheme != null)
            {
                yield return new XAttribute("Theme", SelectedTheme.Value);
            }
            if(SelectedType != null)
            {
                yield return new XAttribute("Type", SelectedType.Value);
            }
        }

        public override IEnumerable<XNode> ConvertToNodes()
        {
            throw new NotImplementedException();
        }

        private readonly ObservableCollection<StringOptionItemViewModel> _outlinedTypes = new()
        {
            new StringOptionItemViewModel("AccountBook","@IconType.Outline.AccountBook"),
            new StringOptionItemViewModel("Aim","@IconType.Outline.Aim"),
            new StringOptionItemViewModel("Alert","@IconType.Outline.Alert"),
            new StringOptionItemViewModel("Alibaba","@IconType.Outline.Alibaba"),
            new StringOptionItemViewModel("AlignCenter","@IconType.Outline.AlignCenter"),
            new StringOptionItemViewModel("AlignLeft","@IconType.Outline.AlignLeft"),
            new StringOptionItemViewModel("AlignRight","@IconType.Outline.AlignRight"),
            new StringOptionItemViewModel("AlipayCircle","@IconType.Outline.AlipayCircle"),
            new StringOptionItemViewModel("Alipay","@IconType.Outline.Alipay"),
            new StringOptionItemViewModel("Aliwangwang","@IconType.Outline.Aliwangwang"),
            new StringOptionItemViewModel("Aliyun","@IconType.Outline.Aliyun"),
            new StringOptionItemViewModel("Amazon","@IconType.Outline.Amazon"),
            new StringOptionItemViewModel("Android","@IconType.Outline.Android"),
            new StringOptionItemViewModel("AntCloud","@IconType.Outline.AntCloud"),
            new StringOptionItemViewModel("AntDesign","@IconType.Outline.AntDesign"),
            new StringOptionItemViewModel("Apartment","@IconType.Outline.Apartment"),
            new StringOptionItemViewModel("Api","@IconType.Outline.Api"),
            new StringOptionItemViewModel("Apple","@IconType.Outline.Apple"),
            new StringOptionItemViewModel("AppstoreAdd","@IconType.Outline.AppstoreAdd"),
            new StringOptionItemViewModel("Appstore","@IconType.Outline.Appstore"),
            new StringOptionItemViewModel("AreaChart","@IconType.Outline.AreaChart"),
            new StringOptionItemViewModel("ArrowDown","@IconType.Outline.ArrowDown"),
            new StringOptionItemViewModel("ArrowLeft","@IconType.Outline.ArrowLeft"),
            new StringOptionItemViewModel("ArrowRight","@IconType.Outline.ArrowRight"),
            new StringOptionItemViewModel("ArrowUp","@IconType.Outline.ArrowUp"),
            new StringOptionItemViewModel("ArrowsAlt","@IconType.Outline.ArrowsAlt"),
            new StringOptionItemViewModel("AudioMuted","@IconType.Outline.AudioMuted"),
            new StringOptionItemViewModel("Audio","@IconType.Outline.Audio"),
            new StringOptionItemViewModel("Audit","@IconType.Outline.Audit"),
            new StringOptionItemViewModel("Backward","@IconType.Outline.Backward"),
            new StringOptionItemViewModel("Bank","@IconType.Outline.Bank"),
            new StringOptionItemViewModel("BarChart","@IconType.Outline.BarChart"),
            new StringOptionItemViewModel("Barcode","@IconType.Outline.Barcode"),
            new StringOptionItemViewModel("Bars","@IconType.Outline.Bars"),
            new StringOptionItemViewModel("BehanceSquare","@IconType.Outline.BehanceSquare"),
            new StringOptionItemViewModel("Behance","@IconType.Outline.Behance"),
            new StringOptionItemViewModel("Bell","@IconType.Outline.Bell"),
            new StringOptionItemViewModel("BgColors","@IconType.Outline.BgColors"),
            new StringOptionItemViewModel("Block","@IconType.Outline.Block"),
            new StringOptionItemViewModel("Bold","@IconType.Outline.Bold"),
            new StringOptionItemViewModel("Book","@IconType.Outline.Book"),
            new StringOptionItemViewModel("BorderBottom","@IconType.Outline.BorderBottom"),
            new StringOptionItemViewModel("BorderHorizontal","@IconType.Outline.BorderHorizontal"),
            new StringOptionItemViewModel("BorderInner","@IconType.Outline.BorderInner"),
            new StringOptionItemViewModel("BorderLeft","@IconType.Outline.BorderLeft"),
            new StringOptionItemViewModel("BorderOuter","@IconType.Outline.BorderOuter"),
            new StringOptionItemViewModel("BorderRight","@IconType.Outline.BorderRight"),
            new StringOptionItemViewModel("BorderTop","@IconType.Outline.BorderTop"),
            new StringOptionItemViewModel("BorderVerticle","@IconType.Outline.BorderVerticle"),
            new StringOptionItemViewModel("Border","@IconType.Outline.Border"),
            new StringOptionItemViewModel("BorderlessTable","@IconType.Outline.BorderlessTable"),
            new StringOptionItemViewModel("BoxPlot","@IconType.Outline.BoxPlot"),
            new StringOptionItemViewModel("Branches","@IconType.Outline.Branches"),
            new StringOptionItemViewModel("Bug","@IconType.Outline.Bug"),
            new StringOptionItemViewModel("Build","@IconType.Outline.Build"),
            new StringOptionItemViewModel("Bulb","@IconType.Outline.Bulb"),
            new StringOptionItemViewModel("Calculator","@IconType.Outline.Calculator"),
            new StringOptionItemViewModel("Calendar","@IconType.Outline.Calendar"),
            new StringOptionItemViewModel("Camera","@IconType.Outline.Camera"),
            new StringOptionItemViewModel("Car","@IconType.Outline.Car"),
            new StringOptionItemViewModel("CaretDown","@IconType.Outline.CaretDown"),
            new StringOptionItemViewModel("CaretLeft","@IconType.Outline.CaretLeft"),
            new StringOptionItemViewModel("CaretRight","@IconType.Outline.CaretRight"),
            new StringOptionItemViewModel("CaretUp","@IconType.Outline.CaretUp"),
            new StringOptionItemViewModel("CarryOut","@IconType.Outline.CarryOut"),
            new StringOptionItemViewModel("CheckCircle","@IconType.Outline.CheckCircle"),
            new StringOptionItemViewModel("CheckSquare","@IconType.Outline.CheckSquare"),
            new StringOptionItemViewModel("Check","@IconType.Outline.Check"),
            new StringOptionItemViewModel("Chrome","@IconType.Outline.Chrome"),
            new StringOptionItemViewModel("CiCircle","@IconType.Outline.CiCircle"),
            new StringOptionItemViewModel("Ci","@IconType.Outline.Ci"),
            new StringOptionItemViewModel("Clear","@IconType.Outline.Clear"),
            new StringOptionItemViewModel("ClockCircle","@IconType.Outline.ClockCircle"),
            new StringOptionItemViewModel("CloseCircle","@IconType.Outline.CloseCircle"),
            new StringOptionItemViewModel("CloseSquare","@IconType.Outline.CloseSquare"),
            new StringOptionItemViewModel("Close","@IconType.Outline.Close"),
            new StringOptionItemViewModel("CloudDownload","@IconType.Outline.CloudDownload"),
            new StringOptionItemViewModel("CloudServer","@IconType.Outline.CloudServer"),
            new StringOptionItemViewModel("CloudSync","@IconType.Outline.CloudSync"),
            new StringOptionItemViewModel("CloudUpload","@IconType.Outline.CloudUpload"),
            new StringOptionItemViewModel("Cloud","@IconType.Outline.Cloud"),
            new StringOptionItemViewModel("Cluster","@IconType.Outline.Cluster"),
            new StringOptionItemViewModel("CodeSandbox","@IconType.Outline.CodeSandbox"),
            new StringOptionItemViewModel("Code","@IconType.Outline.Code"),
            new StringOptionItemViewModel("CodepenCircle","@IconType.Outline.CodepenCircle"),
            new StringOptionItemViewModel("Codepen","@IconType.Outline.Codepen"),
            new StringOptionItemViewModel("Coffee","@IconType.Outline.Coffee"),
            new StringOptionItemViewModel("ColumnHeight","@IconType.Outline.ColumnHeight"),
            new StringOptionItemViewModel("ColumnWidth","@IconType.Outline.ColumnWidth"),
            new StringOptionItemViewModel("Comment","@IconType.Outline.Comment"),
            new StringOptionItemViewModel("Compass","@IconType.Outline.Compass"),
            new StringOptionItemViewModel("Compress","@IconType.Outline.Compress"),
            new StringOptionItemViewModel("ConsoleSql","@IconType.Outline.ConsoleSql"),
            new StringOptionItemViewModel("Contacts","@IconType.Outline.Contacts"),
            new StringOptionItemViewModel("Container","@IconType.Outline.Container"),
            new StringOptionItemViewModel("Control","@IconType.Outline.Control"),
            new StringOptionItemViewModel("Copy","@IconType.Outline.Copy"),
            new StringOptionItemViewModel("CopyrightCircle","@IconType.Outline.CopyrightCircle"),
            new StringOptionItemViewModel("Copyright","@IconType.Outline.Copyright"),
            new StringOptionItemViewModel("CreditCard","@IconType.Outline.CreditCard"),
            new StringOptionItemViewModel("Crown","@IconType.Outline.Crown"),
            new StringOptionItemViewModel("CustomerService","@IconType.Outline.CustomerService"),
            new StringOptionItemViewModel("Dash","@IconType.Outline.Dash"),
            new StringOptionItemViewModel("Dashboard","@IconType.Outline.Dashboard"),
            new StringOptionItemViewModel("Database","@IconType.Outline.Database"),
            new StringOptionItemViewModel("DeleteColumn","@IconType.Outline.DeleteColumn"),
            new StringOptionItemViewModel("DeleteRow","@IconType.Outline.DeleteRow"),
            new StringOptionItemViewModel("Delete","@IconType.Outline.Delete"),
            new StringOptionItemViewModel("DeliveredProcedure","@IconType.Outline.DeliveredProcedure"),
            new StringOptionItemViewModel("DeploymentUnit","@IconType.Outline.DeploymentUnit"),
            new StringOptionItemViewModel("Desktop","@IconType.Outline.Desktop"),
            new StringOptionItemViewModel("Diff","@IconType.Outline.Diff"),
            new StringOptionItemViewModel("Dingding","@IconType.Outline.Dingding"),
            new StringOptionItemViewModel("Dingtalk","@IconType.Outline.Dingtalk"),
            new StringOptionItemViewModel("Disconnect","@IconType.Outline.Disconnect"),
            new StringOptionItemViewModel("Dislike","@IconType.Outline.Dislike"),
            new StringOptionItemViewModel("DollarCircle","@IconType.Outline.DollarCircle"),
            new StringOptionItemViewModel("Dollar","@IconType.Outline.Dollar"),
            new StringOptionItemViewModel("DotChart","@IconType.Outline.DotChart"),
            new StringOptionItemViewModel("DoubleLeft","@IconType.Outline.DoubleLeft"),
            new StringOptionItemViewModel("DoubleRight","@IconType.Outline.DoubleRight"),
            new StringOptionItemViewModel("DownCircle","@IconType.Outline.DownCircle"),
            new StringOptionItemViewModel("DownSquare","@IconType.Outline.DownSquare"),
            new StringOptionItemViewModel("Down","@IconType.Outline.Down"),
            new StringOptionItemViewModel("Download","@IconType.Outline.Download"),
            new StringOptionItemViewModel("Drag","@IconType.Outline.Drag"),
            new StringOptionItemViewModel("DribbbleSquare","@IconType.Outline.DribbbleSquare"),
            new StringOptionItemViewModel("Dribbble","@IconType.Outline.Dribbble"),
            new StringOptionItemViewModel("Dropbox","@IconType.Outline.Dropbox"),
            new StringOptionItemViewModel("Edit","@IconType.Outline.Edit"),
            new StringOptionItemViewModel("Ellipsis","@IconType.Outline.Ellipsis"),
            new StringOptionItemViewModel("Enter","@IconType.Outline.Enter"),
            new StringOptionItemViewModel("Environment","@IconType.Outline.Environment"),
            new StringOptionItemViewModel("EuroCircle","@IconType.Outline.EuroCircle"),
            new StringOptionItemViewModel("Euro","@IconType.Outline.Euro"),
            new StringOptionItemViewModel("Exception","@IconType.Outline.Exception"),
            new StringOptionItemViewModel("ExclamationCircle","@IconType.Outline.ExclamationCircle"),
            new StringOptionItemViewModel("Exclamation","@IconType.Outline.Exclamation"),
            new StringOptionItemViewModel("ExpandAlt","@IconType.Outline.ExpandAlt"),
            new StringOptionItemViewModel("Expand","@IconType.Outline.Expand"),
            new StringOptionItemViewModel("Experiment","@IconType.Outline.Experiment"),
            new StringOptionItemViewModel("Export","@IconType.Outline.Export"),
            new StringOptionItemViewModel("EyeInvisible","@IconType.Outline.EyeInvisible"),
            new StringOptionItemViewModel("Eye","@IconType.Outline.Eye"),
            new StringOptionItemViewModel("Facebook","@IconType.Outline.Facebook"),
            new StringOptionItemViewModel("Fall","@IconType.Outline.Fall"),
            new StringOptionItemViewModel("FastBackward","@IconType.Outline.FastBackward"),
            new StringOptionItemViewModel("FastForward","@IconType.Outline.FastForward"),
            new StringOptionItemViewModel("FieldBinary","@IconType.Outline.FieldBinary"),
            new StringOptionItemViewModel("FieldNumber","@IconType.Outline.FieldNumber"),
            new StringOptionItemViewModel("FieldString","@IconType.Outline.FieldString"),
            new StringOptionItemViewModel("FieldTime","@IconType.Outline.FieldTime"),
            new StringOptionItemViewModel("FileAdd","@IconType.Outline.FileAdd"),
            new StringOptionItemViewModel("FileDone","@IconType.Outline.FileDone"),
            new StringOptionItemViewModel("FileExcel","@IconType.Outline.FileExcel"),
            new StringOptionItemViewModel("FileExclamation","@IconType.Outline.FileExclamation"),
            new StringOptionItemViewModel("FileGif","@IconType.Outline.FileGif"),
            new StringOptionItemViewModel("FileImage","@IconType.Outline.FileImage"),
            new StringOptionItemViewModel("FileJpg","@IconType.Outline.FileJpg"),
            new StringOptionItemViewModel("FileMarkdown","@IconType.Outline.FileMarkdown"),
            new StringOptionItemViewModel("FilePdf","@IconType.Outline.FilePdf"),
            new StringOptionItemViewModel("FilePpt","@IconType.Outline.FilePpt"),
            new StringOptionItemViewModel("FileProtect","@IconType.Outline.FileProtect"),
            new StringOptionItemViewModel("FileSearch","@IconType.Outline.FileSearch"),
            new StringOptionItemViewModel("FileSync","@IconType.Outline.FileSync"),
            new StringOptionItemViewModel("FileText","@IconType.Outline.FileText"),
            new StringOptionItemViewModel("FileUnknown","@IconType.Outline.FileUnknown"),
            new StringOptionItemViewModel("FileWord","@IconType.Outline.FileWord"),
            new StringOptionItemViewModel("FileZip","@IconType.Outline.FileZip"),
            new StringOptionItemViewModel("File","@IconType.Outline.File"),
            new StringOptionItemViewModel("Filter","@IconType.Outline.Filter"),
            new StringOptionItemViewModel("Fire","@IconType.Outline.Fire"),
            new StringOptionItemViewModel("Flag","@IconType.Outline.Flag"),
            new StringOptionItemViewModel("FolderAdd","@IconType.Outline.FolderAdd"),
            new StringOptionItemViewModel("FolderOpen","@IconType.Outline.FolderOpen"),
            new StringOptionItemViewModel("FolderView","@IconType.Outline.FolderView"),
            new StringOptionItemViewModel("Folder","@IconType.Outline.Folder"),
            new StringOptionItemViewModel("FontColors","@IconType.Outline.FontColors"),
            new StringOptionItemViewModel("FontSize","@IconType.Outline.FontSize"),
            new StringOptionItemViewModel("Fork","@IconType.Outline.Fork"),
            new StringOptionItemViewModel("Form","@IconType.Outline.Form"),
            new StringOptionItemViewModel("FormatPainter","@IconType.Outline.FormatPainter"),
            new StringOptionItemViewModel("Forward","@IconType.Outline.Forward"),
            new StringOptionItemViewModel("Frown","@IconType.Outline.Frown"),
            new StringOptionItemViewModel("FullscreenExit","@IconType.Outline.FullscreenExit"),
            new StringOptionItemViewModel("Fullscreen","@IconType.Outline.Fullscreen"),
            new StringOptionItemViewModel("Function","@IconType.Outline.Function"),
            new StringOptionItemViewModel("FundProjectionScreen","@IconType.Outline.FundProjectionScreen"),
            new StringOptionItemViewModel("FundView","@IconType.Outline.FundView"),
            new StringOptionItemViewModel("Fund","@IconType.Outline.Fund"),
            new StringOptionItemViewModel("FunnelPlot","@IconType.Outline.FunnelPlot"),
            new StringOptionItemViewModel("Gateway","@IconType.Outline.Gateway"),
            new StringOptionItemViewModel("Gif","@IconType.Outline.Gif"),
            new StringOptionItemViewModel("Gift","@IconType.Outline.Gift"),
            new StringOptionItemViewModel("Github","@IconType.Outline.Github"),
            new StringOptionItemViewModel("Gitlab","@IconType.Outline.Gitlab"),
            new StringOptionItemViewModel("Global","@IconType.Outline.Global"),
            new StringOptionItemViewModel("Gold","@IconType.Outline.Gold"),
            new StringOptionItemViewModel("GooglePlus","@IconType.Outline.GooglePlus"),
            new StringOptionItemViewModel("Google","@IconType.Outline.Google"),
            new StringOptionItemViewModel("Group","@IconType.Outline.Group"),
            new StringOptionItemViewModel("Hdd","@IconType.Outline.Hdd"),
            new StringOptionItemViewModel("Heart","@IconType.Outline.Heart"),
            new StringOptionItemViewModel("HeatMap","@IconType.Outline.HeatMap"),
            new StringOptionItemViewModel("Highlight","@IconType.Outline.Highlight"),
            new StringOptionItemViewModel("History","@IconType.Outline.History"),
            new StringOptionItemViewModel("Home","@IconType.Outline.Home"),
            new StringOptionItemViewModel("Hourglass","@IconType.Outline.Hourglass"),
            new StringOptionItemViewModel("Html5","@IconType.Outline.Html5"),
            new StringOptionItemViewModel("Idcard","@IconType.Outline.Idcard"),
            new StringOptionItemViewModel("Ie","@IconType.Outline.Ie"),
            new StringOptionItemViewModel("Import","@IconType.Outline.Import"),
            new StringOptionItemViewModel("Inbox","@IconType.Outline.Inbox"),
            new StringOptionItemViewModel("InfoCircle","@IconType.Outline.InfoCircle"),
            new StringOptionItemViewModel("Info","@IconType.Outline.Info"),
            new StringOptionItemViewModel("InsertRowAbove","@IconType.Outline.InsertRowAbove"),
            new StringOptionItemViewModel("InsertRowBelow","@IconType.Outline.InsertRowBelow"),
            new StringOptionItemViewModel("InsertRowLeft","@IconType.Outline.InsertRowLeft"),
            new StringOptionItemViewModel("InsertRowRight","@IconType.Outline.InsertRowRight"),
            new StringOptionItemViewModel("Instagram","@IconType.Outline.Instagram"),
            new StringOptionItemViewModel("Insurance","@IconType.Outline.Insurance"),
            new StringOptionItemViewModel("Interaction","@IconType.Outline.Interaction"),
            new StringOptionItemViewModel("IssuesClose","@IconType.Outline.IssuesClose"),
            new StringOptionItemViewModel("Italic","@IconType.Outline.Italic"),
            new StringOptionItemViewModel("Key","@IconType.Outline.Key"),
            new StringOptionItemViewModel("Laptop","@IconType.Outline.Laptop"),
            new StringOptionItemViewModel("Layout","@IconType.Outline.Layout"),
            new StringOptionItemViewModel("LeftCircle","@IconType.Outline.LeftCircle"),
            new StringOptionItemViewModel("LeftSquare","@IconType.Outline.LeftSquare"),
            new StringOptionItemViewModel("Left","@IconType.Outline.Left"),
            new StringOptionItemViewModel("Like","@IconType.Outline.Like"),
            new StringOptionItemViewModel("LineChart","@IconType.Outline.LineChart"),
            new StringOptionItemViewModel("LineHeight","@IconType.Outline.LineHeight"),
            new StringOptionItemViewModel("Line","@IconType.Outline.Line"),
            new StringOptionItemViewModel("Link","@IconType.Outline.Link"),
            new StringOptionItemViewModel("Linkedin","@IconType.Outline.Linkedin"),
            new StringOptionItemViewModel("Loading3Quarters","@IconType.Outline.Loading3Quarters"),
            new StringOptionItemViewModel("Loading","@IconType.Outline.Loading"),
            new StringOptionItemViewModel("Lock","@IconType.Outline.Lock"),
            new StringOptionItemViewModel("Login","@IconType.Outline.Login"),
            new StringOptionItemViewModel("Logout","@IconType.Outline.Logout"),
            new StringOptionItemViewModel("MacCommand","@IconType.Outline.MacCommand"),
            new StringOptionItemViewModel("Mail","@IconType.Outline.Mail"),
            new StringOptionItemViewModel("Man","@IconType.Outline.Man"),
            new StringOptionItemViewModel("MedicineBox","@IconType.Outline.MedicineBox"),
            new StringOptionItemViewModel("MediumWorkmark","@IconType.Outline.MediumWorkmark"),
            new StringOptionItemViewModel("Medium","@IconType.Outline.Medium"),
            new StringOptionItemViewModel("Meh","@IconType.Outline.Meh"),
            new StringOptionItemViewModel("MenuFold","@IconType.Outline.MenuFold"),
            new StringOptionItemViewModel("MenuUnfold","@IconType.Outline.MenuUnfold"),
            new StringOptionItemViewModel("Menu","@IconType.Outline.Menu"),
            new StringOptionItemViewModel("MergeCells","@IconType.Outline.MergeCells"),
            new StringOptionItemViewModel("Message","@IconType.Outline.Message"),
            new StringOptionItemViewModel("MinusCircle","@IconType.Outline.MinusCircle"),
            new StringOptionItemViewModel("MinusSquare","@IconType.Outline.MinusSquare"),
            new StringOptionItemViewModel("Minus","@IconType.Outline.Minus"),
            new StringOptionItemViewModel("Mobile","@IconType.Outline.Mobile"),
            new StringOptionItemViewModel("MoneyCollect","@IconType.Outline.MoneyCollect"),
            new StringOptionItemViewModel("Monitor","@IconType.Outline.Monitor"),
            new StringOptionItemViewModel("More","@IconType.Outline.More"),
            new StringOptionItemViewModel("NodeCollapse","@IconType.Outline.NodeCollapse"),
            new StringOptionItemViewModel("NodeExpand","@IconType.Outline.NodeExpand"),
            new StringOptionItemViewModel("NodeIndex","@IconType.Outline.NodeIndex"),
            new StringOptionItemViewModel("Notification","@IconType.Outline.Notification"),
            new StringOptionItemViewModel("Number","@IconType.Outline.Number"),
            new StringOptionItemViewModel("OneToOne","@IconType.Outline.OneToOne"),
            new StringOptionItemViewModel("OrderedList","@IconType.Outline.OrderedList"),
            new StringOptionItemViewModel("PaperClip","@IconType.Outline.PaperClip"),
            new StringOptionItemViewModel("Partition","@IconType.Outline.Partition"),
            new StringOptionItemViewModel("PauseCircle","@IconType.Outline.PauseCircle"),
            new StringOptionItemViewModel("Pause","@IconType.Outline.Pause"),
            new StringOptionItemViewModel("PayCircle","@IconType.Outline.PayCircle"),
            new StringOptionItemViewModel("Percentage","@IconType.Outline.Percentage"),
            new StringOptionItemViewModel("Phone","@IconType.Outline.Phone"),
            new StringOptionItemViewModel("PicCenter","@IconType.Outline.PicCenter"),
            new StringOptionItemViewModel("PicLeft","@IconType.Outline.PicLeft"),
            new StringOptionItemViewModel("PicRight","@IconType.Outline.PicRight"),
            new StringOptionItemViewModel("Picture","@IconType.Outline.Picture"),
            new StringOptionItemViewModel("PieChart","@IconType.Outline.PieChart"),
            new StringOptionItemViewModel("PlayCircle","@IconType.Outline.PlayCircle"),
            new StringOptionItemViewModel("PlaySquare","@IconType.Outline.PlaySquare"),
            new StringOptionItemViewModel("PlusCircle","@IconType.Outline.PlusCircle"),
            new StringOptionItemViewModel("PlusSquare","@IconType.Outline.PlusSquare"),
            new StringOptionItemViewModel("Plus","@IconType.Outline.Plus"),
            new StringOptionItemViewModel("PoundCircle","@IconType.Outline.PoundCircle"),
            new StringOptionItemViewModel("Pound","@IconType.Outline.Pound"),
            new StringOptionItemViewModel("Poweroff","@IconType.Outline.Poweroff"),
            new StringOptionItemViewModel("Printer","@IconType.Outline.Printer"),
            new StringOptionItemViewModel("Profile","@IconType.Outline.Profile"),
            new StringOptionItemViewModel("Project","@IconType.Outline.Project"),
            new StringOptionItemViewModel("PropertySafety","@IconType.Outline.PropertySafety"),
            new StringOptionItemViewModel("PullRequest","@IconType.Outline.PullRequest"),
            new StringOptionItemViewModel("Pushpin","@IconType.Outline.Pushpin"),
            new StringOptionItemViewModel("Qq","@IconType.Outline.Qq"),
            new StringOptionItemViewModel("Qrcode","@IconType.Outline.Qrcode"),
            new StringOptionItemViewModel("QuestionCircle","@IconType.Outline.QuestionCircle"),
            new StringOptionItemViewModel("Question","@IconType.Outline.Question"),
            new StringOptionItemViewModel("RadarChart","@IconType.Outline.RadarChart"),
            new StringOptionItemViewModel("RadiusBottomleft","@IconType.Outline.RadiusBottomleft"),
            new StringOptionItemViewModel("RadiusBottomright","@IconType.Outline.RadiusBottomright"),
            new StringOptionItemViewModel("RadiusSetting","@IconType.Outline.RadiusSetting"),
            new StringOptionItemViewModel("RadiusUpleft","@IconType.Outline.RadiusUpleft"),
            new StringOptionItemViewModel("RadiusUpright","@IconType.Outline.RadiusUpright"),
            new StringOptionItemViewModel("Read","@IconType.Outline.Read"),
            new StringOptionItemViewModel("Reconciliation","@IconType.Outline.Reconciliation"),
            new StringOptionItemViewModel("RedEnvelope","@IconType.Outline.RedEnvelope"),
            new StringOptionItemViewModel("Reddit","@IconType.Outline.Reddit"),
            new StringOptionItemViewModel("Redo","@IconType.Outline.Redo"),
            new StringOptionItemViewModel("Reload","@IconType.Outline.Reload"),
            new StringOptionItemViewModel("Rest","@IconType.Outline.Rest"),
            new StringOptionItemViewModel("Retweet","@IconType.Outline.Retweet"),
            new StringOptionItemViewModel("RightCircle","@IconType.Outline.RightCircle"),
            new StringOptionItemViewModel("RightSquare","@IconType.Outline.RightSquare"),
            new StringOptionItemViewModel("Right","@IconType.Outline.Right"),
            new StringOptionItemViewModel("Rise","@IconType.Outline.Rise"),
            new StringOptionItemViewModel("Robot","@IconType.Outline.Robot"),
            new StringOptionItemViewModel("Rocket","@IconType.Outline.Rocket"),
            new StringOptionItemViewModel("Rollback","@IconType.Outline.Rollback"),
            new StringOptionItemViewModel("RotateLeft","@IconType.Outline.RotateLeft"),
            new StringOptionItemViewModel("RotateRight","@IconType.Outline.RotateRight"),
            new StringOptionItemViewModel("SafetyCertificate","@IconType.Outline.SafetyCertificate"),
            new StringOptionItemViewModel("Safety","@IconType.Outline.Safety"),
            new StringOptionItemViewModel("Save","@IconType.Outline.Save"),
            new StringOptionItemViewModel("Scan","@IconType.Outline.Scan"),
            new StringOptionItemViewModel("Schedule","@IconType.Outline.Schedule"),
            new StringOptionItemViewModel("Scissor","@IconType.Outline.Scissor"),
            new StringOptionItemViewModel("Search","@IconType.Outline.Search"),
            new StringOptionItemViewModel("SecurityScan","@IconType.Outline.SecurityScan"),
            new StringOptionItemViewModel("Select","@IconType.Outline.Select"),
            new StringOptionItemViewModel("Send","@IconType.Outline.Send"),
            new StringOptionItemViewModel("Setting","@IconType.Outline.Setting"),
            new StringOptionItemViewModel("Shake","@IconType.Outline.Shake"),
            new StringOptionItemViewModel("ShareAlt","@IconType.Outline.ShareAlt"),
            new StringOptionItemViewModel("Shop","@IconType.Outline.Shop"),
            new StringOptionItemViewModel("ShoppingCart","@IconType.Outline.ShoppingCart"),
            new StringOptionItemViewModel("Shopping","@IconType.Outline.Shopping"),
            new StringOptionItemViewModel("Shrink","@IconType.Outline.Shrink"),
            new StringOptionItemViewModel("Sisternode","@IconType.Outline.Sisternode"),
            new StringOptionItemViewModel("Sketch","@IconType.Outline.Sketch"),
            new StringOptionItemViewModel("Skin","@IconType.Outline.Skin"),
            new StringOptionItemViewModel("Skype","@IconType.Outline.Skype"),
            new StringOptionItemViewModel("SlackSquare","@IconType.Outline.SlackSquare"),
            new StringOptionItemViewModel("Slack","@IconType.Outline.Slack"),
            new StringOptionItemViewModel("Sliders","@IconType.Outline.Sliders"),
            new StringOptionItemViewModel("SmallDash","@IconType.Outline.SmallDash"),
            new StringOptionItemViewModel("Smile","@IconType.Outline.Smile"),
            new StringOptionItemViewModel("Snippets","@IconType.Outline.Snippets"),
            new StringOptionItemViewModel("Solution","@IconType.Outline.Solution"),
            new StringOptionItemViewModel("SortAscending","@IconType.Outline.SortAscending"),
            new StringOptionItemViewModel("SortDescending","@IconType.Outline.SortDescending"),
            new StringOptionItemViewModel("Sound","@IconType.Outline.Sound"),
            new StringOptionItemViewModel("SplitCells","@IconType.Outline.SplitCells"),
            new StringOptionItemViewModel("Star","@IconType.Outline.Star"),
            new StringOptionItemViewModel("StepBackward","@IconType.Outline.StepBackward"),
            new StringOptionItemViewModel("StepForward","@IconType.Outline.StepForward"),
            new StringOptionItemViewModel("Stock","@IconType.Outline.Stock"),
            new StringOptionItemViewModel("Stop","@IconType.Outline.Stop"),
            new StringOptionItemViewModel("Strikethrough","@IconType.Outline.Strikethrough"),
            new StringOptionItemViewModel("Subnode","@IconType.Outline.Subnode"),
            new StringOptionItemViewModel("SwapLeft","@IconType.Outline.SwapLeft"),
            new StringOptionItemViewModel("SwapRight","@IconType.Outline.SwapRight"),
            new StringOptionItemViewModel("Swap","@IconType.Outline.Swap"),
            new StringOptionItemViewModel("Switcher","@IconType.Outline.Switcher"),
            new StringOptionItemViewModel("Sync","@IconType.Outline.Sync"),
            new StringOptionItemViewModel("Table","@IconType.Outline.Table"),
            new StringOptionItemViewModel("Tablet","@IconType.Outline.Tablet"),
            new StringOptionItemViewModel("Tag","@IconType.Outline.Tag"),
            new StringOptionItemViewModel("Tags","@IconType.Outline.Tags"),
            new StringOptionItemViewModel("TaobaoCircle","@IconType.Outline.TaobaoCircle"),
            new StringOptionItemViewModel("Taobao","@IconType.Outline.Taobao"),
            new StringOptionItemViewModel("Team","@IconType.Outline.Team"),
            new StringOptionItemViewModel("Thunderbolt","@IconType.Outline.Thunderbolt"),
            new StringOptionItemViewModel("ToTop","@IconType.Outline.ToTop"),
            new StringOptionItemViewModel("Tool","@IconType.Outline.Tool"),
            new StringOptionItemViewModel("TrademarkCircle","@IconType.Outline.TrademarkCircle"),
            new StringOptionItemViewModel("Trademark","@IconType.Outline.Trademark"),
            new StringOptionItemViewModel("Transaction","@IconType.Outline.Transaction"),
            new StringOptionItemViewModel("Translation","@IconType.Outline.Translation"),
            new StringOptionItemViewModel("Trophy","@IconType.Outline.Trophy"),
            new StringOptionItemViewModel("Twitter","@IconType.Outline.Twitter"),
            new StringOptionItemViewModel("Underline","@IconType.Outline.Underline"),
            new StringOptionItemViewModel("Undo","@IconType.Outline.Undo"),
            new StringOptionItemViewModel("Ungroup","@IconType.Outline.Ungroup"),
            new StringOptionItemViewModel("Unlock","@IconType.Outline.Unlock"),
            new StringOptionItemViewModel("UnorderedList","@IconType.Outline.UnorderedList"),
            new StringOptionItemViewModel("UpCircle","@IconType.Outline.UpCircle"),
            new StringOptionItemViewModel("UpSquare","@IconType.Outline.UpSquare"),
            new StringOptionItemViewModel("Up","@IconType.Outline.Up"),
            new StringOptionItemViewModel("Upload","@IconType.Outline.Upload"),
            new StringOptionItemViewModel("Usb","@IconType.Outline.Usb"),
            new StringOptionItemViewModel("UserAdd","@IconType.Outline.UserAdd"),
            new StringOptionItemViewModel("UserDelete","@IconType.Outline.UserDelete"),
            new StringOptionItemViewModel("UserSwitch","@IconType.Outline.UserSwitch"),
            new StringOptionItemViewModel("User","@IconType.Outline.User"),
            new StringOptionItemViewModel("UsergroupAdd","@IconType.Outline.UsergroupAdd"),
            new StringOptionItemViewModel("UsergroupDelete","@IconType.Outline.UsergroupDelete"),
            new StringOptionItemViewModel("Verified","@IconType.Outline.Verified"),
            new StringOptionItemViewModel("VerticalAlignBottom","@IconType.Outline.VerticalAlignBottom"),
            new StringOptionItemViewModel("VerticalAlignMiddle","@IconType.Outline.VerticalAlignMiddle"),
            new StringOptionItemViewModel("VerticalAlignTop","@IconType.Outline.VerticalAlignTop"),
            new StringOptionItemViewModel("VerticalLeft","@IconType.Outline.VerticalLeft"),
            new StringOptionItemViewModel("VerticalRight","@IconType.Outline.VerticalRight"),
            new StringOptionItemViewModel("VideoCameraAdd","@IconType.Outline.VideoCameraAdd"),
            new StringOptionItemViewModel("VideoCamera","@IconType.Outline.VideoCamera"),
            new StringOptionItemViewModel("Wallet","@IconType.Outline.Wallet"),
            new StringOptionItemViewModel("Warning","@IconType.Outline.Warning"),
            new StringOptionItemViewModel("Wechat","@IconType.Outline.Wechat"),
            new StringOptionItemViewModel("WeiboCircle","@IconType.Outline.WeiboCircle"),
            new StringOptionItemViewModel("WeiboSquare","@IconType.Outline.WeiboSquare"),
            new StringOptionItemViewModel("Weibo","@IconType.Outline.Weibo"),
            new StringOptionItemViewModel("WhatsApp","@IconType.Outline.WhatsApp"),
            new StringOptionItemViewModel("Wifi","@IconType.Outline.Wifi"),
            new StringOptionItemViewModel("Windows","@IconType.Outline.Windows"),
            new StringOptionItemViewModel("Woman","@IconType.Outline.Woman"),
            new StringOptionItemViewModel("Yahoo","@IconType.Outline.Yahoo"),
            new StringOptionItemViewModel("Youtube","@IconType.Outline.Youtube"),
            new StringOptionItemViewModel("Yuque","@IconType.Outline.Yuque"),
            new StringOptionItemViewModel("Zhihu","@IconType.Outline.Zhihu"),
            new StringOptionItemViewModel("ZoomIn","@IconType.Outline.ZoomIn"),


        };

        private readonly ObservableCollection<StringOptionItemViewModel> _filledTypes = new()
        {
            new StringOptionItemViewModel("AccountBook","@IconType.Fill.AccountBook"),
            new StringOptionItemViewModel("Alert","@IconType.Fill.Alert"),
            new StringOptionItemViewModel("AlipayCircle","@IconType.Fill.AlipayCircle"),
            new StringOptionItemViewModel("AlipaySquare","@IconType.Fill.AlipaySquare"),
            new StringOptionItemViewModel("Aliwangwang","@IconType.Fill.Aliwangwang"),
            new StringOptionItemViewModel("AmazonCircle","@IconType.Fill.AmazonCircle"),
            new StringOptionItemViewModel("AmazonSquare","@IconType.Fill.AmazonSquare"),
            new StringOptionItemViewModel("Android","@IconType.Fill.Android"),
            new StringOptionItemViewModel("Api","@IconType.Fill.Api"),
            new StringOptionItemViewModel("Apple","@IconType.Fill.Apple"),
            new StringOptionItemViewModel("Appstore","@IconType.Fill.Appstore"),
            new StringOptionItemViewModel("Audio","@IconType.Fill.Audio"),
            new StringOptionItemViewModel("Backward","@IconType.Fill.Backward"),
            new StringOptionItemViewModel("Bank","@IconType.Fill.Bank"),
            new StringOptionItemViewModel("BehanceCircle","@IconType.Fill.BehanceCircle"),
            new StringOptionItemViewModel("BehanceSquare","@IconType.Fill.BehanceSquare"),
            new StringOptionItemViewModel("Bell","@IconType.Fill.Bell"),
            new StringOptionItemViewModel("Book","@IconType.Fill.Book"),
            new StringOptionItemViewModel("BoxPlot","@IconType.Fill.BoxPlot"),
            new StringOptionItemViewModel("Bug","@IconType.Fill.Bug"),
            new StringOptionItemViewModel("Build","@IconType.Fill.Build"),
            new StringOptionItemViewModel("Bulb","@IconType.Fill.Bulb"),
            new StringOptionItemViewModel("Calculator","@IconType.Fill.Calculator"),
            new StringOptionItemViewModel("Calendar","@IconType.Fill.Calendar"),
            new StringOptionItemViewModel("Camera","@IconType.Fill.Camera"),
            new StringOptionItemViewModel("Car","@IconType.Fill.Car"),
            new StringOptionItemViewModel("CaretDown","@IconType.Fill.CaretDown"),
            new StringOptionItemViewModel("CaretLeft","@IconType.Fill.CaretLeft"),
            new StringOptionItemViewModel("CaretRight","@IconType.Fill.CaretRight"),
            new StringOptionItemViewModel("CaretUp","@IconType.Fill.CaretUp"),
            new StringOptionItemViewModel("CarryOut","@IconType.Fill.CarryOut"),
            new StringOptionItemViewModel("CheckCircle","@IconType.Fill.CheckCircle"),
            new StringOptionItemViewModel("CheckSquare","@IconType.Fill.CheckSquare"),
            new StringOptionItemViewModel("Chrome","@IconType.Fill.Chrome"),
            new StringOptionItemViewModel("CiCircle","@IconType.Fill.CiCircle"),
            new StringOptionItemViewModel("ClockCircle","@IconType.Fill.ClockCircle"),
            new StringOptionItemViewModel("CloseCircle","@IconType.Fill.CloseCircle"),
            new StringOptionItemViewModel("CloseSquare","@IconType.Fill.CloseSquare"),
            new StringOptionItemViewModel("Cloud","@IconType.Fill.Cloud"),
            new StringOptionItemViewModel("CodeSandboxCircle","@IconType.Fill.CodeSandboxCircle"),
            new StringOptionItemViewModel("CodeSandboxSquare","@IconType.Fill.CodeSandboxSquare"),
            new StringOptionItemViewModel("Code","@IconType.Fill.Code"),
            new StringOptionItemViewModel("CodepenCircle","@IconType.Fill.CodepenCircle"),
            new StringOptionItemViewModel("CodepenSquare","@IconType.Fill.CodepenSquare"),
            new StringOptionItemViewModel("Compass","@IconType.Fill.Compass"),
            new StringOptionItemViewModel("Contacts","@IconType.Fill.Contacts"),
            new StringOptionItemViewModel("Container","@IconType.Fill.Container"),
            new StringOptionItemViewModel("Control","@IconType.Fill.Control"),
            new StringOptionItemViewModel("Copy","@IconType.Fill.Copy"),
            new StringOptionItemViewModel("CopyrightCircle","@IconType.Fill.CopyrightCircle"),
            new StringOptionItemViewModel("CreditCard","@IconType.Fill.CreditCard"),
            new StringOptionItemViewModel("Crown","@IconType.Fill.Crown"),
            new StringOptionItemViewModel("CustomerService","@IconType.Fill.CustomerService"),
            new StringOptionItemViewModel("Dashboard","@IconType.Fill.Dashboard"),
            new StringOptionItemViewModel("Database","@IconType.Fill.Database"),
            new StringOptionItemViewModel("Delete","@IconType.Fill.Delete"),
            new StringOptionItemViewModel("Diff","@IconType.Fill.Diff"),
            new StringOptionItemViewModel("DingtalkCircle","@IconType.Fill.DingtalkCircle"),
            new StringOptionItemViewModel("DingtalkSquare","@IconType.Fill.DingtalkSquare"),
            new StringOptionItemViewModel("Dislike","@IconType.Fill.Dislike"),
            new StringOptionItemViewModel("DollarCircle","@IconType.Fill.DollarCircle"),
            new StringOptionItemViewModel("DownCircle","@IconType.Fill.DownCircle"),
            new StringOptionItemViewModel("DownSquare","@IconType.Fill.DownSquare"),
            new StringOptionItemViewModel("DribbbleCircle","@IconType.Fill.DribbbleCircle"),
            new StringOptionItemViewModel("DribbbleSquare","@IconType.Fill.DribbbleSquare"),
            new StringOptionItemViewModel("DropboxCircle","@IconType.Fill.DropboxCircle"),
            new StringOptionItemViewModel("DropboxSquare","@IconType.Fill.DropboxSquare"),
            new StringOptionItemViewModel("Edit","@IconType.Fill.Edit"),
            new StringOptionItemViewModel("Environment","@IconType.Fill.Environment"),
            new StringOptionItemViewModel("EuroCircle","@IconType.Fill.EuroCircle"),
            new StringOptionItemViewModel("ExclamationCircle","@IconType.Fill.ExclamationCircle"),
            new StringOptionItemViewModel("Experiment","@IconType.Fill.Experiment"),
            new StringOptionItemViewModel("EyeInvisible","@IconType.Fill.EyeInvisible"),
            new StringOptionItemViewModel("Eye","@IconType.Fill.Eye"),
            new StringOptionItemViewModel("Facebook","@IconType.Fill.Facebook"),
            new StringOptionItemViewModel("FastBackward","@IconType.Fill.FastBackward"),
            new StringOptionItemViewModel("FastForward","@IconType.Fill.FastForward"),
            new StringOptionItemViewModel("FileAdd","@IconType.Fill.FileAdd"),
            new StringOptionItemViewModel("FileExcel","@IconType.Fill.FileExcel"),
            new StringOptionItemViewModel("FileExclamation","@IconType.Fill.FileExclamation"),
            new StringOptionItemViewModel("FileImage","@IconType.Fill.FileImage"),
            new StringOptionItemViewModel("FileMarkdown","@IconType.Fill.FileMarkdown"),
            new StringOptionItemViewModel("FilePdf","@IconType.Fill.FilePdf"),
            new StringOptionItemViewModel("FilePpt","@IconType.Fill.FilePpt"),
            new StringOptionItemViewModel("FileText","@IconType.Fill.FileText"),
            new StringOptionItemViewModel("FileUnknown","@IconType.Fill.FileUnknown"),
            new StringOptionItemViewModel("FileWord","@IconType.Fill.FileWord"),
            new StringOptionItemViewModel("FileZip","@IconType.Fill.FileZip"),
            new StringOptionItemViewModel("File","@IconType.Fill.File"),
            new StringOptionItemViewModel("Filter","@IconType.Fill.Filter"),
            new StringOptionItemViewModel("Fire","@IconType.Fill.Fire"),
            new StringOptionItemViewModel("Flag","@IconType.Fill.Flag"),
            new StringOptionItemViewModel("FolderAdd","@IconType.Fill.FolderAdd"),
            new StringOptionItemViewModel("FolderOpen","@IconType.Fill.FolderOpen"),
            new StringOptionItemViewModel("Folder","@IconType.Fill.Folder"),
            new StringOptionItemViewModel("FormatPainter","@IconType.Fill.FormatPainter"),
            new StringOptionItemViewModel("Forward","@IconType.Fill.Forward"),
            new StringOptionItemViewModel("Frown","@IconType.Fill.Frown"),
            new StringOptionItemViewModel("Fund","@IconType.Fill.Fund"),
            new StringOptionItemViewModel("FunnelPlot","@IconType.Fill.FunnelPlot"),
            new StringOptionItemViewModel("Gift","@IconType.Fill.Gift"),
            new StringOptionItemViewModel("Github","@IconType.Fill.Github"),
            new StringOptionItemViewModel("Gitlab","@IconType.Fill.Gitlab"),
            new StringOptionItemViewModel("Gold","@IconType.Fill.Gold"),
            new StringOptionItemViewModel("Golden","@IconType.Fill.Golden"),
            new StringOptionItemViewModel("GoogleCircle","@IconType.Fill.GoogleCircle"),
            new StringOptionItemViewModel("GooglePlusCircle","@IconType.Fill.GooglePlusCircle"),
            new StringOptionItemViewModel("GooglePlusSquare","@IconType.Fill.GooglePlusSquare"),
            new StringOptionItemViewModel("GoogleSquare","@IconType.Fill.GoogleSquare"),
            new StringOptionItemViewModel("Hdd","@IconType.Fill.Hdd"),
            new StringOptionItemViewModel("Heart","@IconType.Fill.Heart"),
            new StringOptionItemViewModel("Highlight","@IconType.Fill.Highlight"),
            new StringOptionItemViewModel("Home","@IconType.Fill.Home"),
            new StringOptionItemViewModel("Hourglass","@IconType.Fill.Hourglass"),
            new StringOptionItemViewModel("Html5","@IconType.Fill.Html5"),
            new StringOptionItemViewModel("Idcard","@IconType.Fill.Idcard"),
            new StringOptionItemViewModel("IeCircle","@IconType.Fill.IeCircle"),
            new StringOptionItemViewModel("IeSquare","@IconType.Fill.IeSquare"),
            new StringOptionItemViewModel("InfoCircle","@IconType.Fill.InfoCircle"),
            new StringOptionItemViewModel("Instagram","@IconType.Fill.Instagram"),
            new StringOptionItemViewModel("Insurance","@IconType.Fill.Insurance"),
            new StringOptionItemViewModel("Interaction","@IconType.Fill.Interaction"),
            new StringOptionItemViewModel("Layout","@IconType.Fill.Layout"),
            new StringOptionItemViewModel("LeftCircle","@IconType.Fill.LeftCircle"),
            new StringOptionItemViewModel("LeftSquare","@IconType.Fill.LeftSquare"),
            new StringOptionItemViewModel("Like","@IconType.Fill.Like"),
            new StringOptionItemViewModel("Linkedin","@IconType.Fill.Linkedin"),
            new StringOptionItemViewModel("Lock","@IconType.Fill.Lock"),
            new StringOptionItemViewModel("MacCommand","@IconType.Fill.MacCommand"),
            new StringOptionItemViewModel("Mail","@IconType.Fill.Mail"),
            new StringOptionItemViewModel("MedicineBox","@IconType.Fill.MedicineBox"),
            new StringOptionItemViewModel("MediumCircle","@IconType.Fill.MediumCircle"),
            new StringOptionItemViewModel("MediumSquare","@IconType.Fill.MediumSquare"),
            new StringOptionItemViewModel("Meh","@IconType.Fill.Meh"),
            new StringOptionItemViewModel("Message","@IconType.Fill.Message"),
            new StringOptionItemViewModel("MinusCircle","@IconType.Fill.MinusCircle"),
            new StringOptionItemViewModel("MinusSquare","@IconType.Fill.MinusSquare"),
            new StringOptionItemViewModel("Mobile","@IconType.Fill.Mobile"),
            new StringOptionItemViewModel("MoneyCollect","@IconType.Fill.MoneyCollect"),
            new StringOptionItemViewModel("Notification","@IconType.Fill.Notification"),
            new StringOptionItemViewModel("PauseCircle","@IconType.Fill.PauseCircle"),
            new StringOptionItemViewModel("PayCircle","@IconType.Fill.PayCircle"),
            new StringOptionItemViewModel("Phone","@IconType.Fill.Phone"),
            new StringOptionItemViewModel("Picture","@IconType.Fill.Picture"),
            new StringOptionItemViewModel("PieChart","@IconType.Fill.PieChart"),
            new StringOptionItemViewModel("PlayCircle","@IconType.Fill.PlayCircle"),
            new StringOptionItemViewModel("PlaySquare","@IconType.Fill.PlaySquare"),
            new StringOptionItemViewModel("PlusCircle","@IconType.Fill.PlusCircle"),
            new StringOptionItemViewModel("PlusSquare","@IconType.Fill.PlusSquare"),
            new StringOptionItemViewModel("PoundCircle","@IconType.Fill.PoundCircle"),
            new StringOptionItemViewModel("Printer","@IconType.Fill.Printer"),
            new StringOptionItemViewModel("Profile","@IconType.Fill.Profile"),
            new StringOptionItemViewModel("Project","@IconType.Fill.Project"),
            new StringOptionItemViewModel("PropertySafety","@IconType.Fill.PropertySafety"),
            new StringOptionItemViewModel("Pushpin","@IconType.Fill.Pushpin"),
            new StringOptionItemViewModel("QqCircle","@IconType.Fill.QqCircle"),
            new StringOptionItemViewModel("QqSquare","@IconType.Fill.QqSquare"),
            new StringOptionItemViewModel("QuestionCircle","@IconType.Fill.QuestionCircle"),
            new StringOptionItemViewModel("Read","@IconType.Fill.Read"),
            new StringOptionItemViewModel("Reconciliation","@IconType.Fill.Reconciliation"),
            new StringOptionItemViewModel("RedEnvelope","@IconType.Fill.RedEnvelope"),
            new StringOptionItemViewModel("RedditCircle","@IconType.Fill.RedditCircle"),
            new StringOptionItemViewModel("RedditSquare","@IconType.Fill.RedditSquare"),
            new StringOptionItemViewModel("Rest","@IconType.Fill.Rest"),
            new StringOptionItemViewModel("RightCircle","@IconType.Fill.RightCircle"),
            new StringOptionItemViewModel("RightSquare","@IconType.Fill.RightSquare"),
            new StringOptionItemViewModel("Robot","@IconType.Fill.Robot"),
            new StringOptionItemViewModel("Rocket","@IconType.Fill.Rocket"),
            new StringOptionItemViewModel("SafetyCertificate","@IconType.Fill.SafetyCertificate"),
            new StringOptionItemViewModel("Save","@IconType.Fill.Save"),
            new StringOptionItemViewModel("Schedule","@IconType.Fill.Schedule"),
            new StringOptionItemViewModel("SecurityScan","@IconType.Fill.SecurityScan"),
            new StringOptionItemViewModel("Setting","@IconType.Fill.Setting"),
            new StringOptionItemViewModel("Shop","@IconType.Fill.Shop"),
            new StringOptionItemViewModel("Shopping","@IconType.Fill.Shopping"),
            new StringOptionItemViewModel("Signal","@IconType.Fill.Signal"),
            new StringOptionItemViewModel("SketchCircle","@IconType.Fill.SketchCircle"),
            new StringOptionItemViewModel("SketchSquare","@IconType.Fill.SketchSquare"),
            new StringOptionItemViewModel("Skin","@IconType.Fill.Skin"),
            new StringOptionItemViewModel("Skype","@IconType.Fill.Skype"),
            new StringOptionItemViewModel("SlackCircle","@IconType.Fill.SlackCircle"),
            new StringOptionItemViewModel("SlackSquare","@IconType.Fill.SlackSquare"),
            new StringOptionItemViewModel("Sliders","@IconType.Fill.Sliders"),
            new StringOptionItemViewModel("Smile","@IconType.Fill.Smile"),
            new StringOptionItemViewModel("Snippets","@IconType.Fill.Snippets"),
            new StringOptionItemViewModel("Sound","@IconType.Fill.Sound"),
            new StringOptionItemViewModel("Star","@IconType.Fill.Star"),
            new StringOptionItemViewModel("StepBackward","@IconType.Fill.StepBackward"),
            new StringOptionItemViewModel("StepForward","@IconType.Fill.StepForward"),
            new StringOptionItemViewModel("Stop","@IconType.Fill.Stop"),
            new StringOptionItemViewModel("Switcher","@IconType.Fill.Switcher"),
            new StringOptionItemViewModel("Tablet","@IconType.Fill.Tablet"),
            new StringOptionItemViewModel("Tag","@IconType.Fill.Tag"),
            new StringOptionItemViewModel("Tags","@IconType.Fill.Tags"),
            new StringOptionItemViewModel("TaobaoCircle","@IconType.Fill.TaobaoCircle"),
            new StringOptionItemViewModel("TaobaoSquare","@IconType.Fill.TaobaoSquare"),
            new StringOptionItemViewModel("Thunderbolt","@IconType.Fill.Thunderbolt"),
            new StringOptionItemViewModel("Tool","@IconType.Fill.Tool"),
            new StringOptionItemViewModel("TrademarkCircle","@IconType.Fill.TrademarkCircle"),
            new StringOptionItemViewModel("Trophy","@IconType.Fill.Trophy"),
            new StringOptionItemViewModel("TwitterCircle","@IconType.Fill.TwitterCircle"),
            new StringOptionItemViewModel("TwitterSquare","@IconType.Fill.TwitterSquare"),
            new StringOptionItemViewModel("Unlock","@IconType.Fill.Unlock"),
            new StringOptionItemViewModel("UpCircle","@IconType.Fill.UpCircle"),
            new StringOptionItemViewModel("UpSquare","@IconType.Fill.UpSquare"),
            new StringOptionItemViewModel("Usb","@IconType.Fill.Usb"),
            new StringOptionItemViewModel("VideoCamera","@IconType.Fill.VideoCamera"),
            new StringOptionItemViewModel("Wallet","@IconType.Fill.Wallet"),
            new StringOptionItemViewModel("Warning","@IconType.Fill.Warning"),
            new StringOptionItemViewModel("Wechat","@IconType.Fill.Wechat"),
            new StringOptionItemViewModel("WeiboCircle","@IconType.Fill.WeiboCircle"),
            new StringOptionItemViewModel("WeiboSquare","@IconType.Fill.WeiboSquare"),
            new StringOptionItemViewModel("Windows","@IconType.Fill.Windows"),
            new StringOptionItemViewModel("Yahoo","@IconType.Fill.Yahoo"),
            new StringOptionItemViewModel("Youtube","@IconType.Fill.Youtube"),
            new StringOptionItemViewModel("Yuque","@IconType.Fill.Yuque"),
            new StringOptionItemViewModel("ZhihuCircle","@IconType.Fill.ZhihuCircle"),
            new StringOptionItemViewModel("ZhihuSquare","@IconType.Fill.ZhihuSquare"),
        };

        private readonly ObservableCollection<StringOptionItemViewModel> _twoToneTypes = new()
        {
            new StringOptionItemViewModel("AccountBook","@IconType.TwoTone.AccountBook"),
            new StringOptionItemViewModel("Alert","@IconType.TwoTone.Alert"),
            new StringOptionItemViewModel("Api","@IconType.TwoTone.Api"),
            new StringOptionItemViewModel("Appstore","@IconType.TwoTone.Appstore"),
            new StringOptionItemViewModel("Audio","@IconType.TwoTone.Audio"),
            new StringOptionItemViewModel("Bank","@IconType.TwoTone.Bank"),
            new StringOptionItemViewModel("Bell","@IconType.TwoTone.Bell"),
            new StringOptionItemViewModel("Book","@IconType.TwoTone.Book"),
            new StringOptionItemViewModel("BoxPlot","@IconType.TwoTone.BoxPlot"),
            new StringOptionItemViewModel("Bug","@IconType.TwoTone.Bug"),
            new StringOptionItemViewModel("Build","@IconType.TwoTone.Build"),
            new StringOptionItemViewModel("Bulb","@IconType.TwoTone.Bulb"),
            new StringOptionItemViewModel("Calculator","@IconType.TwoTone.Calculator"),
            new StringOptionItemViewModel("Calendar","@IconType.TwoTone.Calendar"),
            new StringOptionItemViewModel("Camera","@IconType.TwoTone.Camera"),
            new StringOptionItemViewModel("Car","@IconType.TwoTone.Car"),
            new StringOptionItemViewModel("CarryOut","@IconType.TwoTone.CarryOut"),
            new StringOptionItemViewModel("CheckCircle","@IconType.TwoTone.CheckCircle"),
            new StringOptionItemViewModel("CheckSquare","@IconType.TwoTone.CheckSquare"),
            new StringOptionItemViewModel("CiCircle","@IconType.TwoTone.CiCircle"),
            new StringOptionItemViewModel("Ci","@IconType.TwoTone.Ci"),
            new StringOptionItemViewModel("ClockCircle","@IconType.TwoTone.ClockCircle"),
            new StringOptionItemViewModel("CloseCircle","@IconType.TwoTone.CloseCircle"),
            new StringOptionItemViewModel("CloseSquare","@IconType.TwoTone.CloseSquare"),
            new StringOptionItemViewModel("Cloud","@IconType.TwoTone.Cloud"),
            new StringOptionItemViewModel("Code","@IconType.TwoTone.Code"),
            new StringOptionItemViewModel("Compass","@IconType.TwoTone.Compass"),
            new StringOptionItemViewModel("Contacts","@IconType.TwoTone.Contacts"),
            new StringOptionItemViewModel("Container","@IconType.TwoTone.Container"),
            new StringOptionItemViewModel("Control","@IconType.TwoTone.Control"),
            new StringOptionItemViewModel("Copy","@IconType.TwoTone.Copy"),
            new StringOptionItemViewModel("CopyrightCircle","@IconType.TwoTone.CopyrightCircle"),
            new StringOptionItemViewModel("Copyright","@IconType.TwoTone.Copyright"),
            new StringOptionItemViewModel("CreditCard","@IconType.TwoTone.CreditCard"),
            new StringOptionItemViewModel("Crown","@IconType.TwoTone.Crown"),
            new StringOptionItemViewModel("CustomerService","@IconType.TwoTone.CustomerService"),
            new StringOptionItemViewModel("Dashboard","@IconType.TwoTone.Dashboard"),
            new StringOptionItemViewModel("Database","@IconType.TwoTone.Database"),
            new StringOptionItemViewModel("Delete","@IconType.TwoTone.Delete"),
            new StringOptionItemViewModel("Diff","@IconType.TwoTone.Diff"),
            new StringOptionItemViewModel("Dislike","@IconType.TwoTone.Dislike"),
            new StringOptionItemViewModel("DollarCircle","@IconType.TwoTone.DollarCircle"),
            new StringOptionItemViewModel("Dollar","@IconType.TwoTone.Dollar"),
            new StringOptionItemViewModel("DownCircle","@IconType.TwoTone.DownCircle"),
            new StringOptionItemViewModel("DownSquare","@IconType.TwoTone.DownSquare"),
            new StringOptionItemViewModel("Edit","@IconType.TwoTone.Edit"),
            new StringOptionItemViewModel("Environment","@IconType.TwoTone.Environment"),
            new StringOptionItemViewModel("EuroCircle","@IconType.TwoTone.EuroCircle"),
            new StringOptionItemViewModel("Euro","@IconType.TwoTone.Euro"),
            new StringOptionItemViewModel("ExclamationCircle","@IconType.TwoTone.ExclamationCircle"),
            new StringOptionItemViewModel("Experiment","@IconType.TwoTone.Experiment"),
            new StringOptionItemViewModel("EyeInvisible","@IconType.TwoTone.EyeInvisible"),
            new StringOptionItemViewModel("Eye","@IconType.TwoTone.Eye"),
            new StringOptionItemViewModel("FileAdd","@IconType.TwoTone.FileAdd"),
            new StringOptionItemViewModel("FileExcel","@IconType.TwoTone.FileExcel"),
            new StringOptionItemViewModel("FileExclamation","@IconType.TwoTone.FileExclamation"),
            new StringOptionItemViewModel("FileImage","@IconType.TwoTone.FileImage"),
            new StringOptionItemViewModel("FileMarkdown","@IconType.TwoTone.FileMarkdown"),
            new StringOptionItemViewModel("FilePdf","@IconType.TwoTone.FilePdf"),
            new StringOptionItemViewModel("FilePpt","@IconType.TwoTone.FilePpt"),
            new StringOptionItemViewModel("FileText","@IconType.TwoTone.FileText"),
            new StringOptionItemViewModel("FileUnknown","@IconType.TwoTone.FileUnknown"),
            new StringOptionItemViewModel("FileWord","@IconType.TwoTone.FileWord"),
            new StringOptionItemViewModel("FileZip","@IconType.TwoTone.FileZip"),
            new StringOptionItemViewModel("File","@IconType.TwoTone.File"),
            new StringOptionItemViewModel("Filter","@IconType.TwoTone.Filter"),
            new StringOptionItemViewModel("Fire","@IconType.TwoTone.Fire"),
            new StringOptionItemViewModel("Flag","@IconType.TwoTone.Flag"),
            new StringOptionItemViewModel("FolderAdd","@IconType.TwoTone.FolderAdd"),
            new StringOptionItemViewModel("FolderOpen","@IconType.TwoTone.FolderOpen"),
            new StringOptionItemViewModel("Folder","@IconType.TwoTone.Folder"),
            new StringOptionItemViewModel("Frown","@IconType.TwoTone.Frown"),
            new StringOptionItemViewModel("Fund","@IconType.TwoTone.Fund"),
            new StringOptionItemViewModel("FunnelPlot","@IconType.TwoTone.FunnelPlot"),
            new StringOptionItemViewModel("Gift","@IconType.TwoTone.Gift"),
            new StringOptionItemViewModel("Gold","@IconType.TwoTone.Gold"),
            new StringOptionItemViewModel("Hdd","@IconType.TwoTone.Hdd"),
            new StringOptionItemViewModel("Heart","@IconType.TwoTone.Heart"),
            new StringOptionItemViewModel("Highlight","@IconType.TwoTone.Highlight"),
            new StringOptionItemViewModel("Home","@IconType.TwoTone.Home"),
            new StringOptionItemViewModel("Hourglass","@IconType.TwoTone.Hourglass"),
            new StringOptionItemViewModel("Html5","@IconType.TwoTone.Html5"),
            new StringOptionItemViewModel("Idcard","@IconType.TwoTone.Idcard"),
            new StringOptionItemViewModel("InfoCircle","@IconType.TwoTone.InfoCircle"),
            new StringOptionItemViewModel("Insurance","@IconType.TwoTone.Insurance"),
            new StringOptionItemViewModel("Interaction","@IconType.TwoTone.Interaction"),
            new StringOptionItemViewModel("Layout","@IconType.TwoTone.Layout"),
            new StringOptionItemViewModel("LeftCircle","@IconType.TwoTone.LeftCircle"),
            new StringOptionItemViewModel("LeftSquare","@IconType.TwoTone.LeftSquare"),
            new StringOptionItemViewModel("Like","@IconType.TwoTone.Like"),
            new StringOptionItemViewModel("Lock","@IconType.TwoTone.Lock"),
            new StringOptionItemViewModel("Mail","@IconType.TwoTone.Mail"),
            new StringOptionItemViewModel("MedicineBox","@IconType.TwoTone.MedicineBox"),
            new StringOptionItemViewModel("Meh","@IconType.TwoTone.Meh"),
            new StringOptionItemViewModel("Message","@IconType.TwoTone.Message"),
            new StringOptionItemViewModel("MinusCircle","@IconType.TwoTone.MinusCircle"),
            new StringOptionItemViewModel("MinusSquare","@IconType.TwoTone.MinusSquare"),
            new StringOptionItemViewModel("Mobile","@IconType.TwoTone.Mobile"),
            new StringOptionItemViewModel("MoneyCollect","@IconType.TwoTone.MoneyCollect"),
            new StringOptionItemViewModel("Notification","@IconType.TwoTone.Notification"),
            new StringOptionItemViewModel("PauseCircle","@IconType.TwoTone.PauseCircle"),
            new StringOptionItemViewModel("Phone","@IconType.TwoTone.Phone"),
            new StringOptionItemViewModel("Picture","@IconType.TwoTone.Picture"),
            new StringOptionItemViewModel("PieChart","@IconType.TwoTone.PieChart"),
            new StringOptionItemViewModel("PlayCircle","@IconType.TwoTone.PlayCircle"),
            new StringOptionItemViewModel("PlaySquare","@IconType.TwoTone.PlaySquare"),
            new StringOptionItemViewModel("PlusCircle","@IconType.TwoTone.PlusCircle"),
            new StringOptionItemViewModel("PlusSquare","@IconType.TwoTone.PlusSquare"),
            new StringOptionItemViewModel("PoundCircle","@IconType.TwoTone.PoundCircle"),
            new StringOptionItemViewModel("Printer","@IconType.TwoTone.Printer"),
            new StringOptionItemViewModel("Profile","@IconType.TwoTone.Profile"),
            new StringOptionItemViewModel("Project","@IconType.TwoTone.Project"),
            new StringOptionItemViewModel("PropertySafety","@IconType.TwoTone.PropertySafety"),
            new StringOptionItemViewModel("Pushpin","@IconType.TwoTone.Pushpin"),
            new StringOptionItemViewModel("QuestionCircle","@IconType.TwoTone.QuestionCircle"),
            new StringOptionItemViewModel("Reconciliation","@IconType.TwoTone.Reconciliation"),
            new StringOptionItemViewModel("RedEnvelope","@IconType.TwoTone.RedEnvelope"),
            new StringOptionItemViewModel("Rest","@IconType.TwoTone.Rest"),
            new StringOptionItemViewModel("RightCircle","@IconType.TwoTone.RightCircle"),
            new StringOptionItemViewModel("RightSquare","@IconType.TwoTone.RightSquare"),
            new StringOptionItemViewModel("Rocket","@IconType.TwoTone.Rocket"),
            new StringOptionItemViewModel("SafetyCertificate","@IconType.TwoTone.SafetyCertificate"),
            new StringOptionItemViewModel("Save","@IconType.TwoTone.Save"),
            new StringOptionItemViewModel("Schedule","@IconType.TwoTone.Schedule"),
            new StringOptionItemViewModel("SecurityScan","@IconType.TwoTone.SecurityScan"),
            new StringOptionItemViewModel("Setting","@IconType.TwoTone.Setting"),
            new StringOptionItemViewModel("Shop","@IconType.TwoTone.Shop"),
            new StringOptionItemViewModel("Shopping","@IconType.TwoTone.Shopping"),
            new StringOptionItemViewModel("Skin","@IconType.TwoTone.Skin"),
            new StringOptionItemViewModel("Sliders","@IconType.TwoTone.Sliders"),
            new StringOptionItemViewModel("Smile","@IconType.TwoTone.Smile"),
            new StringOptionItemViewModel("Snippets","@IconType.TwoTone.Snippets"),
            new StringOptionItemViewModel("Sound","@IconType.TwoTone.Sound"),
            new StringOptionItemViewModel("Star","@IconType.TwoTone.Star"),
            new StringOptionItemViewModel("Stop","@IconType.TwoTone.Stop"),
            new StringOptionItemViewModel("Switcher","@IconType.TwoTone.Switcher"),
            new StringOptionItemViewModel("Tablet","@IconType.TwoTone.Tablet"),
            new StringOptionItemViewModel("Tag","@IconType.TwoTone.Tag"),
            new StringOptionItemViewModel("Tags","@IconType.TwoTone.Tags"),
            new StringOptionItemViewModel("Thunderbolt","@IconType.TwoTone.Thunderbolt"),
            new StringOptionItemViewModel("Tool","@IconType.TwoTone.Tool"),
            new StringOptionItemViewModel("TrademarkCircle","@IconType.TwoTone.TrademarkCircle"),
            new StringOptionItemViewModel("Trophy","@IconType.TwoTone.Trophy"),
            new StringOptionItemViewModel("Unlock","@IconType.TwoTone.Unlock"),
            new StringOptionItemViewModel("UpCircle","@IconType.TwoTone.UpCircle"),
            new StringOptionItemViewModel("UpSquare","@IconType.TwoTone.UpSquare"),
            new StringOptionItemViewModel("Usb","@IconType.TwoTone.Usb"),
            new StringOptionItemViewModel("VideoCamera","@IconType.TwoTone.VideoCamera"),
            new StringOptionItemViewModel("Wallet","@IconType.TwoTone.Wallet"),
            new StringOptionItemViewModel("Warning","@IconType.TwoTone.Warning"),
        };
    }
}
