// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AntDesignToolbox
{
    internal sealed partial class Vsix
    {
        public const string Id = "AntDesignToolbox2019.51a16eaa-eb6e-4e59-9a9d-2d362a914ed6";
        public const string Name = "AntDesignToolbox2019";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Bin Dong";
        public const string Tags = "";
    }
}
