// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AntDesignToolbox.TextTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Code\Galaxism\AntDesignToolbox\src\AntDesignToolbox\TextTemplates\RazorComponentTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class RazorComponentTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("<h3>");
            
            #line 9 "C:\Code\Galaxism\AntDesignToolbox\src\AntDesignToolbox\TextTemplates\RazorComponentTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            
            #line default
            #line hidden
            this.Write("</h3>\r\n");
            
            #line 10 "C:\Code\Galaxism\AntDesignToolbox\src\AntDesignToolbox\TextTemplates\RazorComponentTemplate.tt"
 if(!IndependentCodeBehind) { 
            
            #line default
            #line hidden
            this.Write("@code {\r\n\r\n}\r\n");
            
            #line 14 "C:\Code\Galaxism\AntDesignToolbox\src\AntDesignToolbox\TextTemplates\RazorComponentTemplate.tt"
 } 
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "C:\Code\Galaxism\AntDesignToolbox\src\AntDesignToolbox\TextTemplates\RazorComponentTemplate.tt"

private string _NameField;

/// <summary>
/// Access the Name parameter of the template.
/// </summary>
private string Name
{
    get
    {
        return this._NameField;
    }
}

private string _NamespaceField;

/// <summary>
/// Access the Namespace parameter of the template.
/// </summary>
private string Namespace
{
    get
    {
        return this._NamespaceField;
    }
}

private bool _IndependentCodeBehindField;

/// <summary>
/// Access the IndependentCodeBehind parameter of the template.
/// </summary>
private bool IndependentCodeBehind
{
    get
    {
        return this._IndependentCodeBehindField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool NameValueAcquired = false;
if (this.Session.ContainsKey("Name"))
{
    this._NameField = ((string)(this.Session["Name"]));
    NameValueAcquired = true;
}
if ((NameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Name");
    if ((data != null))
    {
        this._NameField = ((string)(data));
    }
}
bool NamespaceValueAcquired = false;
if (this.Session.ContainsKey("Namespace"))
{
    this._NamespaceField = ((string)(this.Session["Namespace"]));
    NamespaceValueAcquired = true;
}
if ((NamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Namespace");
    if ((data != null))
    {
        this._NamespaceField = ((string)(data));
    }
}
bool IndependentCodeBehindValueAcquired = false;
if (this.Session.ContainsKey("IndependentCodeBehind"))
{
    this._IndependentCodeBehindField = ((bool)(this.Session["IndependentCodeBehind"]));
    IndependentCodeBehindValueAcquired = true;
}
if ((IndependentCodeBehindValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("IndependentCodeBehind");
    if ((data != null))
    {
        this._IndependentCodeBehindField = ((bool)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
