// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AntDesignToolbox
{
    internal sealed partial class Vsix
    {
        public const string Id = "AntDesignToolbox.fc7d754e-7e4b-4b67-9e21-1d44298675e9";
        public const string Name = "AntDesignToolbox";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Bin Dong";
        public const string Tags = "";
    }
}
