// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AntDesignToolbox
{
    internal sealed partial class Vsix
    {
        public const string Id = "AntDesignToolbox.fc7d754e-7e4b-4b67-9e21-1d44298675e9";
        public const string Name = "Ant Design Blazor Toolbox";
        public const string Description = @"Your companion for Ant Design Blazor development.";
        public const string Language = "en-US";
        public const string Version = "0.2";
        public const string Author = "Bin Dong";
        public const string Tags = "";
    }
}
