// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AntDesignToolbox
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AntDesignToolboxString = "ebd88e56-07f7-48b1-b706-49ce325a3002";
        public static Guid AntDesignToolbox = new Guid(AntDesignToolboxString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ControlToolboxCommand = 0x0100;
        public const int AddComponentCommand = 0x0101;
        public const int WrapInDivisionCommand = 0x0102;
        public const int CreateCodeBehindCommand = 0x0103;
        public const int AntDesignMenu = 0x0001;
        public const int AntDesignMenuGroup = 0x0002;
        public const int FolderContextMenuGroup = 0x0003;
        public const int FolderContextMenu = 0x0004;
        public const int EditorContextMenuGroup = 0x0005;
        public const int EditorContextMenu = 0x0006;
        public const int EditorContextMenuMainGroup = 0x0007;
        public const int ItemNodeContextMenuGroup = 0x0008;
        public const int ItemNodeContextMenu = 0x0009;
    }
}